<Project>
    <ItemDefinitionGroup>
        <RustModule Visible="false" />
    </ItemDefinitionGroup>

    <PropertyGroup>
        <RustModulesTemp>$([System.IO.Path]::GetFullPath('$(MSBuildProjectDirectory)\obj\RustModules\'))</RustModulesTemp>
        <RustModulesSrc>$([System.IO.Path]::GetFullPath('$(MSBuildProjectDirectory)\RustModules\'))</RustModulesSrc>
    </PropertyGroup>

    <Target Name="ResolveRustModules"
            Condition="'@(RustModule)' != ''">

        <ItemGroup>
            <_RustModuleSource Include="@(RustModule)">
                <SourceDir>$(RustModulesSrc)%(Identity)\</SourceDir>
                <SourcePath>$(RustModulesSrc)%(Identity)\%(Name).rs</SourcePath>
                <ManifestPath>$(RustModulesSrc)%(Identity)\Cargo.toml</ManifestPath>
                <TempDir>$(RustModulesTemp)%(Identity)</TempDir>
                <CompiledWasm>$(RustModulesTemp)%(Identity)\wasm32-wasip2\release\%(Name).wasm</CompiledWasm>
                <CompiledWat>$(RustModulesTemp)%(Identity)\wasm32-wasip2\release\%(Name).wat</CompiledWat>
                <CompiledWit>$(RustModulesTemp)%(Identity)\wasm32-wasip2\release\%(Name).wit</CompiledWit>
                <OutputLink>RustModules/%(Name)</OutputLink>
            </_RustModuleSource>
        </ItemGroup>
    </Target>

    <Target Name="BuildRustModules"
            BeforeTargets="Build"
            DependsOnTargets="ResolveRustModules"
            Inputs="@(_RustModuleSource->'%(SourcePath)')"
            Outputs="@(_RustModuleSource->'%(CompiledWasm)')">

        <PropertyGroup>
            <_CargoArgs>--target wasm32-wasip2 --release --lib --quiet</_CargoArgs>
        </PropertyGroup>

        <Message Importance="low"
                 Text="Building Rust module: %(_RustModuleSource.SourceDir). TempDir: %(_RustModuleSource.TempDir)" />

        <!-- Delete target directory in source if it exists -->
        <RemoveDir Directories="%(_RustModuleSource.SourceDir)target" Condition="Exists('%(_RustModuleSource.SourceDir)target')" />

        <MakeDir Directories="%(_RustModuleSource.TempDir)" />

        <Exec Command="cargo build $(_CargoArgs) --manifest-path &quot;%(_RustModuleSource.ManifestPath)&quot; --target-dir &quot;%(_RustModuleSource.TempDir)&quot;"
              WorkingDirectory="%(_RustModuleSource.TempDir)"
              ConsoleToMSBuild="true"
              StandardOutputImportance="low" />

        <Error Condition="!Exists('%(_RustModuleSource.CompiledWasm)')"
               Text="Expected Rust module output was not produced: %(_RustModuleSource.CompiledWasm)" />
    </Target>

    <Target Name="ConvertRustModulesWasmToWat"
            BeforeTargets="Build"
            DependsOnTargets="BuildRustModules"
            Inputs="@(_RustModuleSource->'%(CompiledWasm)')"
            Outputs="@(_RustModuleSource->'%(CompiledWat)')">

        <Message Importance="low"
                 Text="Converting Rust module wasm to wat: %(_RustModuleSource.CompiledWasm) to %(_RustModuleSource.CompiledWat)" />

        <Exec Command="wasm-tools print --color never --print-offsets &quot;%(_RustModuleSource.CompiledWasm)&quot; --output &quot;%(_RustModuleSource.CompiledWat)&quot;"
              ConsoleToMSBuild="true"
              StandardOutputImportance="low" />

        <Error Condition="!Exists('%(_RustModuleSource.CompiledWat)')"
               Text="Expected Rust module output was not produced: %(_RustModuleSource.CompiledWat)" />
    </Target>

    <Target Name="GetRustModulesWit"
             BeforeTargets="Build"
             DependsOnTargets="BuildRustModules"
             Inputs="@(_RustModuleSource->'%(CompiledWasm)')"
             Outputs="@(_RustModuleSource->'%(CompiledWit)')">

        <Message Importance="low"
                 Text="Converting Rust module wasm to wit: %(_RustModuleSource.CompiledWasm) to %(_RustModuleSource.CompiledWit)" />

        <Exec Command="wasm-tools component wit --color never &quot;%(_RustModuleSource.CompiledWasm)&quot; --output &quot;%(_RustModuleSource.CompiledWit)&quot;"
              ConsoleToMSBuild="true"
              StandardOutputImportance="low" />

        <Error Condition="!Exists('%(_RustModuleSource.CompiledWit)')"
               Text="Expected Rust module output was not produced: %(_RustModuleSource.CompiledWit)" />
    </Target>

    <!-- Copy the compiled wasm and wat files as content -->
    <Target Name="IncludeRustModulesAsContent"
            DependsOnTargets="ResolveRustModules;BuildRustModules;ConvertRustModulesWasmToWat;GetRustModulesWit"
            BeforeTargets="GetCopyToOutputDirectoryItems"
            Condition="'$(TargetFramework)' != ''">

        <ItemGroup>
            <ContentWithTargetPath Include="%(_RustModuleSource.CompiledWasm)"
                                   TargetPath="%(_RustModuleSource.OutputLink).wasm"
                                   CopyToOutputDirectory="Always"
                                   Visible="false" />
                        
            <ContentWithTargetPath Include="%(_RustModuleSource.CompiledWat)"
                                   TargetPath="%(_RustModuleSource.OutputLink).wat"
                                   CopyToOutputDirectory="Always"
                                   Visible="false" />

            <ContentWithTargetPath Include="%(_RustModuleSource.CompiledWit)"
                                   TargetPath="%(_RustModuleSource.OutputLink).wit"
                                   CopyToOutputDirectory="Always"
                                   Visible="false" />
        </ItemGroup>
    </Target>
</Project>