(component
  (import "demo:resources/handler@0.1.0" (instance $handler
    (export "resource" (type $r (sub resource)))
    (export "[constructor]resource" (func $ctor (param "value" u32) (result (own $r))))
    (export "[method]resource.get" (func $get (param "self" (borrow $r)) (result u32)))
    (export "[static]resource.last" (func $last (result u32)))))
  (alias export $handler "resource" (type $r))
  (alias export $handler "[constructor]resource" (func $ctor))
  (alias export $handler "[method]resource.get" (func $get))
  (alias export $handler "[static]resource.last" (func $last))
  (core func $ctor-lowered (canon lower (func $ctor)))
  (core func $get-lowered (canon lower (func $get)))
  (core func $last-lowered (canon lower (func $last)))
  (core func $drop (canon resource.drop $r))
  (core module $m
    (import "" "ctor" (func $ctor (param i32) (result i32)))
    (import "" "get" (func $get (param i32) (result i32)))
    (import "" "last" (func $last (result i32)))
    (import "" "drop" (func $drop (param i32)))
    (func (export "run") (result i32)
      (local $r i32)
      (local.set $r (call $ctor (i32.const 123)))
      (i32.add
        (call $get (local.get $r))
        (call $last))
      (call $drop (local.get $r))))
  (core instance $imports
    (export "ctor" (func $ctor-lowered))
    (export "get" (func $get-lowered))
    (export "last" (func $last-lowered))
    (export "drop" (func $drop)))
  (core instance $i (instantiate $m (with "" (instance $imports))))
  (type $t (func (result u32)))
  (func $run (type $t) (canon lift (core func $i "run")))
  (export "run" (func $run)))